baseURL = "https://openroadbook.com/"
languageCode = "en-us"
title = "OpenRoadBook"
paginate = 10
enableRobotsTXT = true
googleAnalyticsID = "G-4HPG3G3WNC"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  lastUpdated = "29 Oct 2025"
